services:
  market_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market_monitor
    restart: unless-stopped

    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
    networks:
      - monitor_network

networks:
  monitor_network:
    external: true