services:
  market_monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market_monitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./market_monitor.log:/app/market_monitor.log
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
    networks:
      - monitor_network

networks:
  monitor_network:
    external: true